#pragma once




#define COBALT_MOUSE_BUTTON_1         0
#define COBALT_MOUSE_BUTTON_2         1
#define COBALT_MOUSE_BUTTON_3         2
#define COBALT_MOUSE_BUTTON_4         3
#define COBALT_MOUSE_BUTTON_5         4
#define COBALT_MOUSE_BUTTON_6         5
#define COBALT_MOUSE_BUTTON_7         6
#define COBALT_MOUSE_BUTTON_8         7
#define COBALT_MOUSE_BUTTON_LAST      COBALT_MOUSE_BUTTON_8
#define COBALT_MOUSE_BUTTON_LEFT      COBALT_MOUSE_BUTTON_1
#define COBALT_MOUSE_BUTTON_RIGHT     COBALT_MOUSE_BUTTON_2
#define COBALT_MOUSE_BUTTON_MIDDLE    COBALT_MOUSE_BUTTON_3